### ISSUE TITLE
views: decorators are applied on each call

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/flask-resources#41]
The correct use case would be:

- The method/view gets decorated once
- The decorator is called each time the function is invoked

The current behaviour:

- The method/view is decorated each time a function (get, post, etc.) is invoked. This happens because it is being decorated in the `dispatch_request`.

The ideal would be to decorate each method once, to avoid having the same chain of decorators in every module (e.g. content negotiation happens always, request loading also...)

**EDIT**
Goal of this issue is to refactor `BaseView` to use `decorators` to hold the common decorators. This will:
- decorate in one place the common decorators
- decorate once when `as_view` is called

**Comment by fenekku** [comment]
@Rablo I think this is solved. We decorate in one place (the BaseView) with decorators that apply to all Resource methods and more spericifc method-related decorators can be added on each method separately.

Did you have something else in mind?

**Comment by ppanero** [comment]
The issue still applies, the main problem is that the decoration happens inside the `dispatch_request`. Which means that we are decorating on each request rather than once (at start time of the web app). 

However, if the function invokation is moved to the `__init__` the decorator is not applied to each method but to each class, and therefore not work.

**Comment by fenekku** [comment]
Ok, then we should use the `decorators` class variable from https://github.com/pallets/flask/blob/024f0d384cf5bb65c76ac59f8ddce464b2dc2ca1/src/flask/views.py#L56 . Will amend the issue to this.

**Comment by ppanero** [comment]
@fenekku when using that variable is the second point I was mentioning. Decorators are applied per class, and then not used in every function (get, post, etc). This would need some more research on the inner guts of flask/werkzeug I guess.

**Comment by fenekku** [comment]
> Decorators are applied per class, and then not used in every function (get, post, etc).

I don't think I understand something here... With `View`'s `decorators` the decorators are applied per class and *used* for `get`, `post`, ... When are they not used?

If the issue is about decorators only for some methods and not others, then that is already possible by putting a decorator on some methods and not others. In some cases, we could give extra support such as the 2nd option here: #59 .

**Comment by ppanero** [comment]
Theoretically what you say is right. However, when Alex and I tested it, this:

> I don't think I understand something here... With View's decorators the decorators are applied per class and used for get, post, ... When are they not used?

Did not work. That is why I say it requires more research. Maybe we did something wrong, or maybe it is not working as intended.

**Comment by fenekku** [comment]
Strange, :thinking:  I will check it out this week.

**Comment by fenekku** [comment]
This is what is preventing us from using the built-in `decorators`:

https://github.com/pallets/flask/blob/master/src/flask/app.py#L1852

> return self.view_functions[rule.endpoint](**req.view_args)

because `self` is not passed in for MethodView `decorators` and we need it, we will do without it.
